---

- name: "install system packages"
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - mosquitto

- name: "install websocket script"
  copy:
    dest: /home/pi/websocket.py
    src: websocket.py

- name: "reset websocket autostart"
  cron:
    name: "websocket"
    state: absent

- name: "setup websocket autostart"
  cron:
    name: "websocket"
    job: "/usr/bin/python /home/pi/websocket.py &"
    special_time: reboot
