---

- name: "setup webserver directory"
  become: true
  file:
    path: /var/www
    state: directory
    mode: "u=rwx,g=rx,o=r"
    owner: pi
    group: users

- name: "install index file"
  copy:
    dest: /var/www/index.htm
    src: index.htm

- name: "reset webserver autostart"
  cron:
    name: "webserver"
    state: absent

- name: "setup webserver autostart"
  cron:
    name: "webserver"
    job: "/usr/bin/sudo /usr/bin/python /home/pi/server.py &"
    special_time: reboot
