---

- hosts: control
  serial: 1
  roles:
    - role: ansible
    - role: prometheus
    - role: grafana
    - role: broker

- hosts: all
  serial: 3
  roles:
    - role: network
    - role: packages
    - role: metrics

- hosts: cluster
  serial: 3
  roles:
    - role: cluster

- hosts: camera
  serial: 1
  roles:
    - role: camera

- hosts: kiosk
  serial: 1
  roles:
    - role: kiosk
