---

- hosts: control
  serial: 1
  roles:
    - role: ansible
    - role: prometheus
    - role: grafana
    - role: broker

- hosts: all
  serial: 3
  roles:
    - role: network
    - role: packages
    - role: metrics

- hosts: worker
  serial: 3
  roles:
    - role: worker

- hosts: camera
  serial: 1
  roles:
    - role: camera
    - role: kiosk

- hosts: radio
  serial: 1
  roles:
    - role: radio
