---

- hosts: all
  become: true
  tasks:

  - name: "update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "upgrade"
    apt:
      upgrade: full

- hosts: blinkt
  tasks:

  - name: "client script"
    template:
      dest: /home/pi/client.py
      src: blinkt.py

- hosts: unicornhat
  tasks:

  - name: "client script"
    template:
      dest: /home/pi/client.py
      src: unicorn.py

- hosts: all
  become: true
  tasks:

  - name: "REBOOT"
    command: "/sbin/shutdown -r +1"
    ignore_errors: true
    async: false
    poll: false
