---

- name: "install npm packages"
  npm:
    name: "{{item}}"
    path: /home/pi/
  with_items:
    - mqtt
    - request

- name: "install robot script"
  copy:
    dest: /home/pi/robot.js
    src: robot.js

- name: "reset robot autostart"
  cron:
    name: "cluster"
    state: absent

- name: "setup robot autostart"
  cron:
    name: "cluster"
    job: "/usr/bin/nodejs /home/pi/robot.js &"
    special_time: reboot
